export const LOADING_JSON 			= 'LOADING_JSON'
export const LOAD_JSON_SUCCESS 		= 'LOAD_JSON_SUCCESS'
export const LOAD_JSON_ERROR 		= 'LOAD_JSON_ERROR'

export const CHANGE_ACTIVE_USER 	= 'CHANGE_ACTIVE_USER'
export const CHANGE_SEARCHBAR 		= 'CHANGE_SEARCHBAR'
export const CHANGE_SORT_TYPE 		= 'CHANGE_SORT_TYPE'
export const CHANGE_SORT_DIRECTION 	= 'CHANGE_SORT_DIRECTION'
export const CHANGE_SELECTED_USERS 	= 'CHANGE_SELECTED_USERS'

export const ADD_USER 				= 'ADD_USER'

